spring:
  application:
    name: HRM-USER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_user
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:com/maggie/mappermapper/*Mapper.xml
  type-aliases-package: com.maggie.hrm.domain,com.maggie.hrm.query